//! PTX / CUDA backend — NVIDIA GPU (SM 70–90)
//! Emits PTX assembly from @hw::gpu kernel blocks + host launch stubs.

use super::Backend;
use crate::mir::MirModule;

#[derive(Default)]
pub struct PtxBackend { pub sm_version: String }

impl Backend for PtxBackend {
    fn name(&self) -> &'static str { "ptx" }
    fn lower(&self, modules: &[MirModule]) -> anyhow::Result<String> {
        let sm = if self.sm_version.is_empty() { "sm_90" } else { &self.sm_version };
        let mut out = format!("// Balua PTX backend — target {}\n.version 8.0\n.target {}\n.address_size 64\n\n", sm, sm);
        for m in modules {
            for f in &m.functions {
                if !matches!(f.hardware, Some(crate::ast::HardwareTarget::Gpu)) { continue; }
                out.push_str(&format!(".visible .entry {}(\n  .param .u64 A,\n  .param .u64 B,\n  .param .u64 C\n) {{\n", f.name));
                out.push_str("  .reg .u32 %tid_x, %tid_y;\n  mov.u32 %tid_x, %tid.x;\n  mov.u32 %tid_y, %tid.y;\n  // ... Balua kernel body lowered from MIR\n  ret;\n}\n\n");
                // host stub
                out.push_str(&format!("// Host launch stub for {} — auto-generated by baluac\n", f.name));
                out.push_str(&format!("// cudaLaunchKernel((void*){}, grid, block, args, 0, 0);\n\n", f.name));
            }
        }
        Ok(out)
    }
}
