[package]
name = "blpkg"
version.workspace = true
edition.workspace = true
description = "Balua Package Manager — BPM.exe (PubGrub resolver, builder, registry client)"

[[bin]]
name = "BPM"
path = "src/main.rs"

[[bin]]
name = "blpkg"
path = "src/main.rs"

[dependencies]
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
anyhow.workspace = true
log.workspace = true
env_logger.workspace = true
toml = "0.8"
semver = "1.0"
baluac = { path = "../baluac" }
